name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build 🛠
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main
      - name: Set timezone to EST
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
          timezoneWindows: "Eastern Standard Time"
      - name: Install dependencies 📦
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Debug Environment Variables
        run: printenv | grep -E 'MONGODB_URI|DB_NAME|COLLECTION_NAME'
      - name: Build 🏗
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
        run: python build.py
      - name: Archive production artifacts 📦
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./output/
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download production artifacts 
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./downloaded-build-output/
      - name: Deploy to production 🚀
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./downloaded-build-output/
          port: 21
